matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - gfortran-4.9
      env:
         - MATRIX_EVAL="export CC=gcc-4.9 && export CXX=g++-4.9 && export FC=gfortran-4.9"
      python: "2.7"

language: python
before_install:
  - eval "${MATRIX_EVAL}"
  - echo CC=$CC
  - echo CXX=$CXX
  - echo FC=$FC
  - echo pwd=`pwd`
install:
  - export PATH=${TRAVIS_BUILD_DIR}/dist_install/bin:$PATH
  - export PYTHONPATH=${TRAVIS_BUILD_DIR}/dist_install/share/hhgrid:$PYTHONPATH
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy==1.8.2 scipy
  - autoreconf -i
  - if [ -z $FC ]; then ./configure --disable-fortran --prefix=${TRAVIS_BUILD_DIR}/dist_install; else ./configure --prefix=${TRAVIS_BUILD_DIR}/dist_install; fi
  - make
script:
  - make check
